export const types = {
  LOCATION_CHANGE: '@@router/LOCATION_CHANGE',
  DASHBOARD: '/dashboard',
  DATABASES: '/databases',
  DB_APPS: '/databases/apps',
  DB_APPS_EDIT: '/databases/apps/edit',
  DB_APPS_INSERT: '/databases/apps/insert',
  DB_COMPONENTS: '/databases/components',
  DB_COMPONENTS_EDIT: '/databases/components/edit',
  DB_COMPONENTS_INSERT: '/databases/components/insert',
  DB_NODES: '/databases/nodes',
  DB_NODES_EDIT: '/databases/nodes/edit',
  DB_NODES_INSERT: '/databases/nodes/insert',
  DB_SITES: '/databases/sites',
  DB_SITES_EDIT: '/databases/sites/edit',
  DB_SITES_INSERT: '/databases/sites/insert',
  DB_USERS: '/databases/users',
  DB_USERS_EDIT: '/databases/users/edit',
  DB_USERS_INSERT: '/databases/users/insert',
  USERS: '/users',
  USERS_ADD: '/users?add=true',
  USERS_EDIT: '/users?edit=true',
  USERS_SEARCH: '/users?search=true',
  PERMISSIONS: '/permissions',
  LIVE_CODING: '/live-coding',
};