export const types = {
  FETCH_PERMISSIONS: 'PERMISSIONS_FETCH_PERMISSIONS',
  FETCH_PERMISSIONS_FULFILLED: 'PERMISSIONS_FETCH_PERMISSIONS_FULFILLED',
  FETCH_PERMISSIONS_REJECTED: 'PERMISSIONS_FETCH_PERMISSIONS_REJECTED',

  ADD_ROLE: 'PERMISSIONS_ADD_ROLE',
  EDIT_ROLE: 'PERMISSIONS_EDIT_ROLE',
  DELETE_ROLE: 'PERMISSIONS_DELETE_ROLE',
  GET_CAPS: 'PERMISSIONS_GET_CAPABILITIES',
  ADD_CAP: 'PERMISSIONS_ADD_CAPABILITY',
  EDIT_CAP: 'PERMISSIONS_EDIT_CAPABILITY',
  DELETE_CAP: 'PERMISSIONS_DELETE_CAPABILITY',
}